name: Publish Site

on:
  push:
    branches:
      - java-3301-maven-documentation

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt-hotspot
      - name: Cache Maven Wrapper
        uses: actions/cache@v2
        with:
          path: ./.mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('./.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-maven-wrapper
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: publish site
        run: ./mvnw --batch-mode site-deploy
